[package]
name = "nes-emulator"
version = "0.26.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4" }
env_logger = { version = "0.10" }

[dev-dependencies]
mockall = "0.11.2"
